version: '3.8'
x-fusion: &default-app
  build:
    context: "."
    target: "app" # this app refers a name in docker file that given in FROM keyword
    args:
      - "FLASK_DEBUG=${FLASK_DEBUG:-true}"
  volumes:
    - ".:/fusion"

services:
  web:
    container_name: flask_web
    <<: *default-app
    command: ["gunicorn", "-c", "conf/gunicorn.py", "app.app:create_app('test')", "--log-config", "conf/gunicorn_log.conf"]
    depends_on:
      - db
    ports:
      - "127.0.0.1:5000:5000"
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - "./.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: