
CONF = {
    "missing_header": "timeout headers is missing from the header",
    "unrecognise_header": "Timeout header containes string character",
    "wrong_creds": "You have entred Wrong Credentials",
    "logged_out": "Logged out!",
    'database_error': "An error occurred, possibly due to a database issue",
    "wrong_key": "You have entered the wrong key",
    "data_updated": "Data updated successfully",
    "key_not_found": "Entered key not found in the database",
    "query_error": "There was an error in the queries: {e}",
    "company_already_exist": "The company already exists in the database",
    "company_registerd": "Company registered successfully",
    "company_deleted": "Company successfully deleted",
    "user_created": "User created succesfully you can login now!",
    "user_already_exist": "User already present on the database with <{email}>",
    "user_not_found": "Can not find the user",
    "user_deleted": "User Deleted succesfully",
    "role_already_exist": "Role already exist in the database please use that or change the role name.",
    "role_created": "Record created succesfully!",
    "role_id_missing": "Role ID is missing, please provide the role ID first",
    "role_updated": "Role Updated succesfully!",
    "role_not_exist": "The role is not Exist on the database",
    "role_deleted": "Role Deleted successfully!",
}