from flask.views import MethodView
from flask_smorest import Blueprint
from .schema import UserSchema, UserDelSchema
from .controller import UserController
from flask_jwt_extended import jwt_required

blp = Blueprint("Users", __name__, description="Users Operations")

#define the routes and call the controller
# for a single endpoint I have defined two methods GET and POST
@blp.route("/users")
class Users(MethodView):

    @jwt_required()
    def get(self):
        """it will fetch all the records from the users tables

        Returns:
            json: a list of users details that exclude the password filed
        """
        return UserController.fetch_users()
    
    @blp.arguments(UserSchema)
    def post(self, users_data):
        """For creating new user for authentication and login

        Args:
            users_data (json): some information about the user such as fname, lname, password, email etc.

        Returns:
            json: success or error message depending upon the user exist or not in the databse
        """
        return UserController.create_user(users_data)
    
    @jwt_required()
    @blp.arguments(UserDelSchema)
    def delete(self, user_id):
        """For delet the user form the database it required a id that will fetch the user detail

        Args:
            user_id (json): 32-bit id of a user that is auto-generated by the server

        Returns:
            json: message of success for deleting the user
        """
        return UserController.delete_user(user_id)
    